#!/usr/bin/env python3
# -*- coding:utf-8 -*-

import pickle
import json

d = dict(name = 'Bob', age = 20, score =90)
f = open('test.txt', 'wb') #write (pickle) muse request be bytes
pickle.dump(d, f) # == f.write(pickle.dumps(d))
f.close()
'''d write to f by bytes'''

f = open('test.txt', 'rb')
a = pickle.load(f)
f.close()
'''f loads to a by bytes'''

''' the usage of the pickle.loads'''
l = pickle.dumps(d)
a = pickle.loads(l) ==> dict(name = 'Bob', age = 20, score =90)

''' the usage of JSON'''
f = open('test.txt', 'w') # JSON coding: UTF-8
json.dump(d, f)  # ==> f.write(json.dumps(d))
f.close()

f = open('test'txt', 'r')
a = json.load(f)
f.close()

a = json.loads(json.dumps(d))


'''speclally:  class > JSON'''

class Student(object):
	
	def __init__(self, name, age, score):
		self.name = name
		self.age = age
		self.score = score


a = Student('Bob', '20', '90)
''' Class is not JSON serializable directly'''
'''BUT'''
json.dumps(a, default=lambda obj: obj.__dict__)   # turn instance of class into dict

