#!/usr/bin/env python3
#! -*- decoding: utf-8 -*-

import urllib
import urllib.request
import re

page = 1
url = 'http://www.qiushibaike.com/hot/' + str(page)
headers = {'User-agent' :  'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' }

req = urllib.request.Request(url, headers = headers)
respo = urllib.request.urlopen(req)
data = respo.read().decode('utf-8')
pattern = re.compile(r'<div.*?class="author.*?>.*?<h2>(.*?)</h2>.*?<span>(.*?)</span>.*?</a>(.*?)class="number">(.*?)</i>',re.S)
items = re.findall(pattern, data)



#print(items)


#print(data)

for item in items:
    haveImg = re.search("img", item[2])#判断是否有IMG
    if not haveImg:    #跳过img        
        #print(item[2])
        print('作者：%s\n 内容：%s\n 点赞数：%s\n' % (item[0], item[1], item[3]))

#以上为爬取的核心代码，下面增加交互对象操作

